name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker metropolis-base
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          name: fgborges/jupyter-metropolis/metropolis-base
          workdir: metropolis-base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
      - name: Publish Docker metropolis
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          name: fgborges/jupyter-metropolis/metropolis
          workdir: metropolis
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
